name: Build Project

on:
  workflow_dispatch:

concurrency:
  group: "build-and-upload"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup `node`
        uses: actions/setup-node@v3
        with:
          node-version: '20.10'
      - name: Restore `lively.next` installation
        id: cache-lively
        uses: actions/cache/restore@v3
        env:
          cache-name: lively-repo
          ref: d4c0ac1156d5942d7c2bbaf7829f18a138b2ce6a
        with:
          path: .            
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.ref }}
      - name: Checkout `lively.next`
        if: ${{ steps.cache-lively.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: LivelyKernel/lively.next
          ref: d4c0ac1156d5942d7c2bbaf7829f18a138b2ce6a
      - name: Install `lively.next`
        if: ${{ steps.cache-lively.outputs.cache-hit != 'true' }}
        run: |
          chmod a+x ./install.sh
          ./install.sh --freezer-only
      - name: Save `lively` installation in cache
        if: ${{ steps.cache-lively.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        env:
          cache-name: lively-repo
          ref: d4c0ac1156d5942d7c2bbaf7829f18a138b2ce6a
        with:
          path: .            
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.ref }}     
      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          path: local_projects/nextguys--project-demo
      - name: Checkout Project Dependencies
        uses: actions/checkout@v4
        with:
          repository: nextguys/private-dependency-project
          path: local_projects/nextguys--private-dependency-project/
          ssh-key: ${{ secrets.nextguys_private_dependency_project }}
      - name: Checkout Project Dependencies
        uses: actions/checkout@v4
        with:
          repository: nextguys/private-transitive-dependency-project
          path: local_projects/nextguys--private-transitive-dependency-project/
          ssh-key: ${{ secrets.nextguys_private_transitive_dependency_project }}
      - name: Build Project
        run: npm run build-minified --prefix local_projects/nextguys--project-demo
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: local_projects/nextguys--project-demo/build